# Generated by Django 4.2.3 on 2023-09-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='tax',
            new_name='taxcode',
        ),
    ]
