# Generated by Django 4.2.3 on 2023-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_tax_supplier_taxcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeI', models.DateTimeField(null=True)),
                ('input', models.SmallIntegerField(null=True)),
                ('asset_id', models.SmallIntegerField(null=True)),
                ('asset_name', models.CharField(max_length=80, null=True)),
                ('category_id', models.SmallIntegerField(null=True)),
                ('category_name', models.CharField(max_length=32, null=True)),
                ('timeO', models.DateTimeField(null=True)),
                ('output', models.SmallIntegerField(null=True)),
                ('treatment', models.SmallIntegerField(null=True)),
                ('stock', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'InventoryTmp',
            },
        ),
    ]
