# Generated by Django 4.2.3 on 2023-09-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='unitIN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UnitIN', to='inventory.assetunit'),
        ),
    ]
