# Generated by Django 4.2.3 on 2023-09-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_asset_unitin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='unitIN',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='unitINOUT',
        ),
    ]
