# Generated by Django 4.2.3 on 2023-09-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_asset_unitin_remove_asset_unitinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='unitINOUT',
            field=models.IntegerField(default=1),
        ),
    ]
