# Generated by Django 4.2.3 on 2023-09-01 02:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableBType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
            ],
            options={
                'db_table': 'TableBType',
            },
        ),
        migrations.CreateModel(
            name='TableB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabler.tablebtype')),
            ],
            options={
                'db_table': 'TableB',
            },
        ),
    ]
