# Generated by Django 4.2.3 on 2023-09-02 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableb',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='TableBActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_stop', models.DateTimeField()),
                ('table_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabler.tableb')),
            ],
            options={
                'db_table': 'TableBActive',
            },
        ),
    ]
