# Generated by Django 4.2.3 on 2023-09-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0005_alter_tablebactive_time_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableb',
            name='active_time',
            field=models.DateTimeField(null=True),
        ),
    ]
