# Generated by Django 4.2.3 on 2023-09-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytmp'),
        ('tabler', '0006_tableb_active_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_active', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('order_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset')),
            ],
            options={
                'db_table': 'TableBActiveOrder',
            },
        ),
        migrations.DeleteModel(
            name='TableBActiveProcess',
        ),
    ]
