# Generated by Django 4.2.3 on 2023-09-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0007_tablebactiveorder_delete_tablebactiveprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebactiveorder',
            name='order_time',
            field=models.DateTimeField(null=True),
        ),
    ]
