# Generated by Django 4.2.3 on 2023-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0008_alter_tablebactiveorder_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebactiveorder',
            name='order_asset',
            field=models.IntegerField(),
        ),
    ]
