# Generated by Django 4.2.3 on 2023-09-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytmp'),
        ('tabler', '0009_alter_tablebactiveorder_order_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebactiveorder',
            name='order_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset'),
        ),
        migrations.AlterField(
            model_name='tablebactiveorder',
            name='table_active',
            field=models.SmallIntegerField(),
        ),
    ]
