# Generated by Django 4.2.3 on 2023-09-05 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytmp'),
        ('tabler', '0012_rename_tablebactiveassettmp_tablebactiveordertmp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeO', models.DateTimeField(auto_now_add=True)),
                ('userID', models.SmallIntegerField()),
                ('treat', models.IntegerField()),
                ('quantity', models.SmallIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset')),
            ],
            options={
                'db_table': 'TableBActiveAsset',
            },
        ),
    ]
