# Generated by Django 4.2.3 on 2023-09-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0013_tablebactiveasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_time', models.DateTimeField()),
                ('table_active', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'TableBActiveSplit',
            },
        ),
    ]
