# Generated by Django 4.2.3 on 2023-09-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0014_tablebactivesplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveSplitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_table', models.SmallIntegerField()),
                ('order_asset', models.SmallIntegerField()),
                ('quantity', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'TableBActiveSplitOrder',
            },
        ),
    ]
