# Generated by Django 4.2.3 on 2023-09-07 09:51

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0015_tablebactivesplitorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveSplitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_order', models.SmallIntegerField()),
                ('split_minutes', models.SmallIntegerField()),
                ('split_paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('split_paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
            ],
            options={
                'db_table': 'TableBActiveSplitDetails',
            },
        ),
    ]
