# Generated by Django 4.2.3 on 2023-09-08 01:15

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0016_tablebactivesplitdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableBActiveSplitDetails',
        ),
        migrations.AddField(
            model_name='tablebactivesplit',
            name='split_paid',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16),
        ),
        migrations.AddField(
            model_name='tablebactivesplit',
            name='split_paid_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3),
        ),
    ]
