# Generated by Django 4.2.3 on 2023-09-08 07:33

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0017_delete_tablebactivesplitdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveSplitOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_table', models.SmallIntegerField()),
                ('split_time', models.DateTimeField(null=True)),
                ('split_minutes', models.SmallIntegerField(null=True)),
                ('split_order', models.CharField(max_length=80, null=True)),
                ('split_order_quantity', models.SmallIntegerField(null=True)),
                ('split_order_paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('split_order_paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
                ('split_total_paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('split_total_paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
            ],
            options={
                'db_table': 'TableBActiveSplitOrderDetails',
            },
        ),
    ]
