# Generated by Django 4.2.3 on 2023-09-08 13:02

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0018_tablebactivesplitorderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebactivesplitorderdetails',
            name='split_time_paid',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='tablebactivesplitorderdetails',
            name='split_time_paid_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True),
        ),
    ]
