# Generated by Django 4.2.3 on 2023-09-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0019_tablebactivesplitorderdetails_split_time_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebactivesplitorderdetails',
            name='split_order_paid',
        ),
        migrations.RemoveField(
            model_name='tablebactivesplitorderdetails',
            name='split_order_paid_currency',
        ),
        migrations.RemoveField(
            model_name='tablebactivesplitorderdetails',
            name='split_total_paid',
        ),
        migrations.RemoveField(
            model_name='tablebactivesplitorderdetails',
            name='split_total_paid_currency',
        ),
    ]
