# Generated by Django 4.2.3 on 2023-09-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0022_tablebactivesplitorderdetails_split_order_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebactivesplitorderdetails',
            name='split_curr',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
