# Generated by Django 4.2.3 on 2023-09-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0023_tablebactivesplitorderdetails_split_curr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebactiveorder',
            name='quantity_remain',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
