# Generated by Django 4.2.3 on 2023-09-11 14:01

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0025_tablebactivesplit_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=80)),
                ('quantity', models.SmallIntegerField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
                ('paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
            ],
            options={
                'db_table': 'TableBActiveBill',
            },
        ),
    ]
