# Generated by Django 4.2.3 on 2023-09-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0026_tablebactivebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebactivebill',
            name='product',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tablebactivebill',
            name='quantity',
            field=models.SmallIntegerField(null=True),
        ),
    ]
