# Generated by Django 4.2.3 on 2023-09-14 23:32

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0027_alter_tablebactivebill_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBActiveFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_active', models.SmallIntegerField()),
                ('time_start', models.DateTimeField()),
                ('time_ended', models.DateTimeField()),
                ('tips_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3, null=True)),
                ('tips', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16, null=True)),
                ('paid_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('VND', 'VN ₫')], default='VND', editable=False, max_length=3)),
                ('paid', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='VND', max_digits=16)),
            ],
            options={
                'db_table': 'TableBActiveFinish',
            },
        ),
        migrations.DeleteModel(
            name='TableBActiveSplitOrderDetails',
        ),
    ]
