# Generated by Django 4.2.3 on 2023-09-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0028_tablebactivefinish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebactivefinish',
            name='note',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
