# Generated by Django 4.2.3 on 2023-09-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabler', '0029_tablebactivefinish_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tableb',
            table='tableb',
        ),
        migrations.AlterModelTable(
            name='tablebactive',
            table='tablebactive',
        ),
        migrations.AlterModelTable(
            name='tablebactiveasset',
            table='tablebactiveasset',
        ),
        migrations.AlterModelTable(
            name='tablebactivebill',
            table='tablebactivebill',
        ),
        migrations.AlterModelTable(
            name='tablebactivefinish',
            table='tablebactivefinish',
        ),
        migrations.AlterModelTable(
            name='tablebactiveorder',
            table='tablebactiveorder',
        ),
        migrations.AlterModelTable(
            name='tablebactiveordertmp',
            table='tablebactiveordertmp',
        ),
        migrations.AlterModelTable(
            name='tablebactivesplit',
            table='tablebactivesplit',
        ),
        migrations.AlterModelTable(
            name='tablebactivesplitorder',
            table='tablebactivesplitorder',
        ),
        migrations.AlterModelTable(
            name='tablebtype',
            table='tablebtype',
        ),
    ]
