# Generated by Django 4.2.3 on 2023-08-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birthday',
        ),
    ]
